### ISSUE TITLE
Email disappear

### ISSUE THREAD

**Issue by meinagong** [cassidoo/HTML-CSS-Tutorial#9]
hey cassidoo:
thank you very much for your guide help me learn html and css,
I am appreciate it : )

7 - project example.html maybe need you review, because "Contact me" section the email address not display in the browser.
<img width="777" alt="Screen Shot 2020-09-25 at 2 46 10 PM" src="https://user-images.githubusercontent.com/12710153/94235357-00851b80-ff3e-11ea-80cf-9ac1a38be7e5.png">

**Comment by cassidoo** [comment]
Hello! Great catch! So there's a reason for this actually, and that's because of the height of your browser window. If you were to zoom out (Cmd - or Ctrl -, depending on your operating system), the email would show up. I'll make a quick tweak in the CSS to make that not be a problem anymore. Thanks for pointing this out!

**Comment by meinagong** [comment]
zoom out 90% display the email address.
Thank you very much : )
